#
# Helm Defaults
# 
helmDefaults:
  wait: true
  verify: false
  timeout: 600
  recreatePods: false
  force: true

#
# Helm Repositories
#
repositories:
  # Cloud Posse incubator repo of helm charts
  - name: "cloudposse-incubator"
    url: "https://charts.cloudposse.com/incubator/"

#
# Kubernetes Cluster
#
context: '{{ requiredEnv "KUBE_CONTEXT" }}'

#
# Helm Releases
#
releases:
  # Application
  - name: '{{ env "RELEASE_NAME" | default "statup" }}'
    chart: "cloudposse-incubator/monochart"
    version: "0.7.0"
    namespace: '{{ requiredEnv "NAMESPACE" }}'
    labels:
      chart: 'statup'
      component: "app"

    # Override values for this release
    values:
      - image:
          repository: r.cfcr.io/cloudposse/statup
          tag: '{{ requiredEnv "IMAGE_TAG" }}'
          pullPolicy: Always
          pullSecrets:
          - '{{ requiredEnv "NAMESPACE" }}-pull-secret-dockercfg'
        replicaCount: 2

        # Healthcheck probes
        probes:
          livenessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

        # Resource limits
        resources:
          limits:
            cpu: 400m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi

        # Secrets for this app that are available to deployments, jobs and cronjobs
        secrets:
          default:
            enabled: true
            env:
              DB_PASS: '{{ env "DB_PASS" | default "changeme" }}'

        # Config settings for this app
        configMaps:
          default:
            enabled: true
            mountPath: /configs/
            env:
              NAME: '{{ env "NAME" | default "Demo App" }}'
              DESCRIPTION: '{{ env "DESCRIPTION" | default "This is a Statup uptime dashboard" }}'
              VIRTUAL_HOST: '{{ env "APP_HOST" |default "localhost" }}'
              VIRTUAL_PORT: '80'
              DB_CONN: '{{ env "DB_CONN" | default "postgres" }}'
              DB_HOST: '{{ env "DB_HOST" | default "db" }}'
              DB_USER: '{{ env "DB_USER" | default "app" }}'
              DB_DATABASE: '{{ env "DB_DATABASE" | default "default" }}'

        # Service endpoint
        service:
          enabled: true
          type: "ClusterIP"
          externalPort: 80
          internalPort: 8080

        # Ingress rules
        ingress:
          default:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: "true"
              external-dns.alpha.kubernetes.io/target: '{{ requiredEnv "NGINX_INGRESS_HOSTNAME" }}'
              external-dns.alpha.kubernetes.io/ttl: "60"
            hosts:
              {{ requiredEnv "APP_HOST" }}: /
            tls:
            - secretName: {{ requiredEnv "RELEASE_NAME" }}-tls
              hosts:
               - {{ requiredEnv "APP_HOST" }}

        # Deployment configuration
        deployment:
          enabled: true
          strategy:
            type: "RollingUpdate"
            rollingUpdate:
              maxUnavailable: 0
          revisionHistoryLimit: 10

        # Trigger job that runs /db-migrations.sh
        job:
          migrations:
            enabled: false
            activeDeadlineSeconds: 300
            restartPolicy: "Never"
            annotations:
              "helm.sh/hook": "post-install,post-upgrade"
              "helm.sh/hook-delete-policy": "before-hook-creation"
            pod:
              args: ['/db-migrations.sh']

        # CronJob that processes race results every 15 minutes
        cronjob:
          demo:
            enabled: false
            successfulJobsHistoryLimit: 1
            failedJobsHistoryLimit: 1
            concurrencyPolicy: "Forbid"
            schedule: "*/15 * * * *"
            activeDeadlineSeconds: 300
            restartPolicy: "Never"
            pod:
              args: ['/cron.sh']


